# Generated by Django 4.2.23 on 2025-11-17 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("zapi_webhook", "0002_messagelog_external_system_response_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome identificador do token (ex: Sistema XYZ)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Token gerado automaticamente",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Token ativo ou revogado"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True,
                        help_text="Última vez que o token foi usado",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuário que criou o token",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Token de API",
                "verbose_name_plural": "Tokens de API",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApiRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="IP do cliente que fez a requisição"
                    ),
                ),
                (
                    "carga_number",
                    models.CharField(
                        db_index=True,
                        help_text="Número da carga consultada",
                        max_length=20,
                    ),
                ),
                (
                    "request_status",
                    models.CharField(
                        choices=[
                            ("success", "Sucesso"),
                            ("invalid_token", "Token Inválido"),
                            ("invalid_input", "Entrada Inválida"),
                            ("system_error", "Erro do Sistema"),
                            ("timeout", "Timeout"),
                            ("connection_error", "Erro de Conexão"),
                            ("rate_limited", "Rate Limit Excedido"),
                        ],
                        db_index=True,
                        help_text="Status da requisição",
                        max_length=50,
                    ),
                ),
                (
                    "response_status",
                    models.CharField(
                        blank=True,
                        choices=[("0", "Não encontrado"), ("1", "Encontrado")],
                        help_text="Status retornado ao cliente (0 ou 1)",
                        max_length=1,
                    ),
                ),
                (
                    "response_message",
                    models.TextField(
                        blank=True, help_text="Mensagem retornada ao cliente"
                    ),
                ),
                (
                    "internal_system_status_code",
                    models.IntegerField(
                        blank=True,
                        help_text="Código HTTP do sistema interno",
                        null=True,
                    ),
                ),
                (
                    "internal_system_response",
                    models.TextField(
                        blank=True, help_text="Resposta bruta do sistema interno"
                    ),
                ),
                (
                    "processing_time_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Tempo de processamento em milissegundos",
                        null=True,
                    ),
                ),
                (
                    "api_token",
                    models.ForeignKey(
                        blank=True,
                        help_text="Token usado na requisição",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="zapi_webhook.apitoken",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Requisição API",
                "verbose_name_plural": "Logs de Requisições API",
                "ordering": ["-created_at"],
            },
        ),
    ]
