# Generated by Django 4.2.23 on 2025-12-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zapi_webhook", "0003_apitoken_apirequestlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryWebhookLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "message_id",
                    models.CharField(
                        db_index=True,
                        help_text="ID recebido da empresa",
                        max_length=255,
                    ),
                ),
                (
                    "delivery_message",
                    models.TextField(
                        blank=True, help_text="Mensagem de retorno da empresa"
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(help_text="Payload JSON completo recebido"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(help_text="IP da empresa externa"),
                ),
                (
                    "webhook_status",
                    models.CharField(
                        choices=[
                            ("success", "Sucesso - Encaminhado"),
                            ("not_found", "ID não encontrado (404)"),
                            ("forward_error", "Erro ao encaminhar"),
                            ("invalid_payload", "Payload inválido"),
                        ],
                        db_index=True,
                        help_text="Status do processamento do webhook",
                        max_length=50,
                    ),
                ),
                (
                    "internal_route_status_code",
                    models.IntegerField(
                        blank=True, help_text="Código HTTP da rota interna", null=True
                    ),
                ),
                (
                    "internal_route_response",
                    models.TextField(blank=True, help_text="Resposta da rota interna"),
                ),
                (
                    "processing_time_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Tempo de processamento em milissegundos",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Webhook de Entrega",
                "verbose_name_plural": "Logs de Webhook de Entrega",
                "ordering": ["-created_at"],
            },
        ),
    ]
